# Generated by Django 4.1.5 on 2023-01-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='heartIcon',
            field=models.TextField(default='"fa-regular fa-heart"'),
        ),
    ]
