# Generated by Django 4.1.5 on 2023-01-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_hearticon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='heartIcon',
            field=models.TextField(default='<i class="fa-regular fa-heart"></i>'),
        ),
    ]
